- src/index.js
- src/tabs/home/index.js
- src/tabs/more/index.js
Events now lives inside each of the navigators that require it (Home and More) so that it comes in from the side and doesn't reset the Tab Navigator every time you press into an Event for more detail
> [CFDP-380] Moved the Events navigator

- src/features/FeaturesHeader/LiveStreamListFeatureConnected/index.js
Removes an unecessary dark overlay that caused a gray square to be shown behind the circular image for Live Content
> [CFDP-832] Fixes visual bug

- src/features/FeaturesHeader/LiveStreamListFeatureConnected/index.js
Removes an unecessary dark overlay that caused a gray square to be shown behind the circular image for Live Content
> Fixes visual bug

- src/media-player/index.js
**Summary**
This PR fixes this crash.
**Discussion**
It's crashing because the local media player state is empty. I'm not sure how it gets to be null, because the state is initialized by the media player here:
https://github.com/ApollosProject/apollos-apps/blob/c9e60b7efd9bd2c54e6b0d2ef2a1ef77d14c928a/packages/apollos-ui-media-player/src/Provider.js#L198
It may only occur on a fresh app install/login, but even then it should be initialized.
**Testing**
In brief testing, I could not reproduce this, but this defensive line should be in there anyway.
> [Chat] Fix crash when media player state is not initialized

- src/group-single/GroupSingle.js
- fixes Group Members scroll padding bug
- fixes image gradient not lining up with background gradient
- adds typographic rhythm to "Group Members" title
> GroupSingle polish

- .gitignore
- src/group-single/attendMeeting.js
`addMemberAttendance` requires `locationIds` and will error if a group does not have a location/campus in Rock. So, quick fix is to use `checkInCurrentUser` and circle back later on a more robust solution for attendance
> Use checkInCurrentUser for attendance

- patches/react-native-zoom-bridge+1.0.18.patch
- yarn.lock
When you switch to your home screen on Android and go back into the App, click 'Join Meeting' and you should be back in the meeting with no errors.
After you yarn, search for `meetingService.returnToMeeting` in the `react-native-zoom-bridge` node_module and it should be in the `RNZoomBridgeModule.java` three times. Specifically, in the `joinMeetingWithPassword` and `joinMeeting` is where we want to see that method called. This is the code that should be added to those methods by the patch.
```
if(meetingService.getMeetingStatus() != MeetingStatus.MEETING_STATUS_IDLE) {
long lMeetingNo = 0;
try {
lMeetingNo = Long.parseLong(meetingNo);
} catch (NumberFormatException e) {
promise.reject("ERR_ZOOM_START", "Invalid meeting number: " + meetingNo);
return;
} …
```
> Patch Android Zoom bug when you background the app

- src/chat/Channel.js
- src/chat/ChannelsList.js
- src/chat/components/ChannelList/ChannelListHeaderErrorIndicator.js
- src/chat/components/ChannelList/ChannelListHeaderNetworkDownIndicator.js
- src/chat/components/MessageInput.js
- src/chat/components/MessageList/index.js
- src/chat/styles/mapTheme.js
- src/media-player/LiveStreamChat.js
- src/media-player/LiveStreamPlayer.js
**Summary**
This PR updates Chat to use the app theme (and hence dark mode).
**Discussion**
So the stock Stream components were already using a Styled Components theme. Unfortunately, it was not using the Apollos theme, and it was a totally different shape. Rather than re-write all the component styles to use the Apollos theme (someday), I set up a "shim" to map the CF/Apollos theme to what the Stream components expect. This works well.
**Testing**
Enable Dark Mode in Settings and ensure everything looks right.
**Screenshots**
https://drive.google.com/file/d/198MvIkfpeMyO93NDu7BGo7CkYwTKih_K/view?usp=sharing
> [Chat] Dark Mode support

- ios/ChristFellowship.xcodeproj/project.pbxproj
- src/media-player/LiveStreamChat.js
- src/media-player/LiveStreamPlayer.js
- src/media-player/index.js
**Summary**
This PR wires up the client to use the new `chatChannelId` field on the API when creating a channel for a livestream event.
Secondarily, it also inserts event metadata into the channel at creation time. This is not totally necessary at this time, but will be handy in the future should we ever wish to query, render, filter, debug, etc channels via the Stream CLI or otherwise. The metadata is:
- Parent ID (`EventContentItem:1e07e4f2e1b52807e43b2338c73d88ba`)
- Parent title (`Test 24 Hour Live Stream`)
- Event start time (`2020-09-24T04:00:00.000Z`)
- Event end time (`2020-09-25T04:00:00.000Z`)
**Discussion**
**Testing**
Make sure you are running https://github.com/christfellowshipchurch/apollos-api/pull/134 either in master or checked out.
Run this query in Playground.
```gql …
```
> [Chat] Chat Channel ID and Event Metadata

- src/content-single/AddCalEventButton/index.js
- src/content-single/EventContentItem/index.js
- src/content-single/EventDateTimes/index.js
This PR modifies the Livestream event page to allow the user to add an upcoming livestream to their calendar app. Borrows heavily from the Groups add-to-calendar button.
I went back and forth with the layout, but ultimately landed on what  you see below.
From the Home tab, open up the `Tune In Online` event. Pressing on any of the upcoming livestreams should open the add-to-calendar UI with the correct data filled in.
> [Live] Add upcoming to calendar app

- src/group-single/VideoCall.js
Makes it so a group can pass in anything to the `video call link` param in Rock and it will be passed to the `onPress` of the video call button if the video call object does not have a `meetingId`.
> Pass video call link if no meeting id exists

- src/media-player/LiveStreamChat.js
This PR renders the number of users currently watching the livestream in the lower, right-hand corner of the video. It only renders if the number of watchers is > 1. 
**Approach**. This PR listens for an event called `user.watching.start`. To enable this event, I had to enable `Connect Events` in the Stream.io dashboard.
On this event, the app reads the `channel.state.watcher_count` value and renders it. The Stream.io docs have a lot of documentation around "user presence" but it's not clear how or when exactly to use it. I believe this feature is not for what we want, but more for rendering a list of channel members and displaying like a green dot next to those who are online, or present.
**Design** Open to design feedback. I played with different places for this number, but they all …
> [Chat] Show number of users currently watching

- package.json
- src/content-single/EventContentItem/index.js
Temporarily hides the schedule info on an Event until we land the plane on the schema updates and scheduling setup.
> [Events] Hide Events Schedule

- src/content-single/ContentSingle.js
- src/media-player/LiveStreamPlayer.js
- src/media-player/controls/MiniControls.js
- src/media-player/index.js
- src/media-player/mutations.js
This PR adds interactions that are reported to Rock when a user joins and closes a live stream.
TO TEST:
1. Make sure you are on `track-interactions` branch for both the app and api.
2. Set your app .env to point at dev rock. `ROCK_API=https://dev-rock.christfellowship.church/`.
3. Fire up your sim and click on the `Test 24 Hour Live Stream` event. When you click on the `play` button after 10 seconds the `LIVESTREAM_JOINED` interaction should fire and you should see that reflected in the interactions in Rock [Apollos Content Item - 7565](https://dev-rock.christfellowship.church/page/664?ComponentId=169206)
4. If you minimize and then close the mini-player the `LIVESTREAM_CLOSED` interaction will be add to Rock.
_Note:_ You can test this on the prod Rock instance. You just have to track …
> Setup Live Stream Interactions

- .gitignore
- package.json
- scripts/generate-bugsnag-source-map.sh
- scripts/upload-bugsnag-source-map.sh
Adds 2 new scripts along with a bunch of new commands!
**generate-bugsnag-source-map**: Runs a Bugsnag script to create a source map for the given version of the app
**upload-bugsnag-source-map**: Uploads the source map to Bugsnag
Adds 7 new yarn commands in the `package.json`
**generate-source-map:android**: creates an Android source map
**generate-source-map:ios**: creates an iOS source map
**upload-source-map:android**: uploads the Android source map
**upload-source-map:ios**: uploads the iOS source map
**bugsnag-release:android**: runs `generate-` and `upload-` scripts for android
**bugsnag-release:ios**: runs `generate-` and `upload-` scripts for ios
**bugsnag-release**: runs both `bugsnag-release:android` and `bugsnag-ios`
Part of our version release flows needs to include uploading …
> Bugsnag source map generation and upload scripts

- src/media-player/LiveStreamPlayer.js
Undoes a decision I insisted on earlier, which is insist that we wait ~10s before firing the `JOIN_LIVESTREAM` interaction to Rock.
I'm not sure why I insisted on that. And more importantly, to be consistent with the web PR [[LiveStream] LiveStream event join/close interactions](https://github.com/christfellowshipchurch/web-app/pull/216), the timeout needs removed.
We'll err on the generous side for counting `JOIN` interactions.
None
Careful code review is probably enough, but, you can open a live event in the app and [verify the interaction shows up immediately on Rock](https://rock.christfellowship.church/page/664?ComponentId=181648).
None
N/A
**Manual QA**
**Code Review**
> The purpose of PR Review is to _improve the quality of the software._
> Remove timeout delay for consistency with web

- src/client/index.js
- src/features/FeaturesFeed/FeaturesFeedConnected/index.js
When the app moves _back_ into a foreground, active state, refetch data for the Feature Feeds
> Tab refetch policy

- src/context/CurrentUserProvider.js
- src/context/ProvidersStack.js
- src/drawer/Logout.js
- src/hooks/useCurrentUser.js
- src/stream-chat/components/ChatChannelList.js
- src/stream-chat/components/NotificationsToggle.js
- src/stream-chat/context/index.js
- src/stream-chat/hooks/useStreamChatClient.js
- src/stream-chat/index.js
- src/stream-chat/screens/ChatChannelSingle.js
- src/tabs/HeaderButtons.js
- src/tabs/index.js
There was a bug reported that the In App Notification indicator was not accurately displaying when a Notification was read/unread. While investigating, it appeared that there was a conflict between multiple instances of the Stream `chatClient` being created, each of which is returning different data for the `total_unread_count`.
This PR seeks to resolve that problem by reworking the Global State Provider for Stream Chat.
**Global State:** Stream Chat now has a new global state provider which sits at the root of the application. This Provider _only_ provides the current context of Stream. This includes:
* chatClient object
* Connection Status
* Active Channel
* Methods to update/change these values
* Connection/Disconnection methods to trigger new user states
**Current User Provider:** …
> Stream Chat Provider Updates

- src/context/CurrentUserProvider.js
- src/context/NotificationsProvider.js
- src/context/UniversalLinkRouteProvider.js
- src/group-single/Group/Actions.js
- src/group-single/Group/index.js
- src/hooks/useLinkRouter.js
- src/stream-chat/components/ChatChannelList.js
- src/stream-chat/context/index.js
- src/stream-chat/hooks/index.js
- src/stream-chat/hooks/useStreamChatClient.js
- src/stream-chat/screens/ChatChannelSingle.js
Found some additional connection/disconnection issues inside of the Stream Chat set up. Also updates some of the Group rendering logic to better adhere to the new Provider structure.
Removes the ability to query for a Chat Channel from a nodeId from the `StreamChatClientContext`. This is due to the Apollo Client not being accessible inside of this context. I also removed all "cleanup" functions cause it looked like there are quite a few instances in which the cleanup was running and disconnected the user from Stream.
This re-introduces the `"consecutive calls to chatClient.connect"` warning, but it seems to be inconsequential from the testing so far.
[CFDP-1285]
[CFDP-1437]
[CFDP-1285]: https://christfellowshipchurch.atlassian.net/browse/CFDP-1285
[CFDP-1437]: …
> Patch stream chat connection

- fastlane/Fastfile
- fastlane/Matchfile
- fastlane/README.md
- ios/ChristFellowship-tvOS/Info.plist
- ios/ChristFellowship-tvOSTests/Info.plist
- ios/ChristFellowship.xcodeproj/project.pbxproj
- ios/ChristFellowship/Info.plist
- ios/ChristFellowshipTests/Info.plist
- ios/OneSignalNotificationServiceExtension/Info.plist
- ios/OneSignalNotificationServiceExtension/NotificationService.swift
- ios/OneSignalNotificationServiceExtension/OneSignalNotificationServiceExtension.entitlements
- ios/Podfile
- ios/Podfile.lock
- package.json
- src/context/AppBadgeProvider.js
- src/context/NotificationsProvider.js
- src/context/ProvidersStack.js
- src/stream-chat/screens/ChatChannelSingle.js
- yarn.lock
This PR establishes the client-side code required for clearing/setting Notification Badges on the iOS Home Screen App Icon
Run this PR locally and receive a handful of Push Notifications from a Group Message. While the app is open, you should be able to see that the Badge is setting according to the number of unread messages.
This Client Side update does not automatically increment the number from a remote notification. That code is reflected in the server-side patch referenced below
[Loom Demo](https://www.loom.com/share/07ff52a702c7476f83699d6e4ac9c4fb)
[CFDP-1287]
[API Patch for Remote Notifications](https://github.com/christfellowshipchurch/apollos-api/pull/300)
[CFDP-1287]: https://christfellowshipchurch.atlassian.net/browse/CFDP-1287
> Notification Badges

- ios/ChristFellowship.xcodeproj/project.pbxproj
- ios/ChristFellowship/Info.plist
- src/context/AppBadgeProvider.js
- src/context/NotificationsProvider.js
- src/tabs/HeaderButtons.js
* Updates an error with OneSignal not using the updated SDK reference for removing listeners
* Updates the `useEffect` for setting the Badge Icon to ensure that the `badgeRef` is set before interacting
* Sets OneSignal to _not_ automatically remove the badge (we want to set this manually)
* Uses the Badge to set the in-app Notification Badge so that the App Badge and and In-App Badge are always in sync (this has appeared to resolve the issue with syncing between tabs
Load up the app and send some test notifications using the Chat feature. You should notice the Home Screen and In App Badges match as you receive/read messages
| In App | Home Screen |
| --- | --- |
| <img width="300" alt="Screen Shot 2021-07-06 at 4 57 55 PM" src="https://user-images.githubusercontent.com/45076058/124666001-6 …
> Notification badge update

- ios/ChristFellowship-tvOS/Info.plist
- ios/ChristFellowship-tvOSTests/Info.plist
- ios/ChristFellowship.xcodeproj/project.pbxproj
- ios/ChristFellowship/Info.plist
- ios/ChristFellowshipTests/Info.plist
- ios/OneSignalNotificationServiceExtension/Info.plist
- ios/Podfile.lock
- package.json
- yarn.lock
Profile Image uploads were not working on the User Profile. This was tracked down to be an error in React Native that was patched in 0.63.3. Since we were only 1 minor release behind, it felt fine to just upgrade. In preliminary testing, this did not appear to have any side-effects.
Navigate to Connect --> Edit User and upload a new profile image
Profile Image for Anakin Skywalker now appears inside of Rock
[CFDP-1281]
[CFDP-1281]: https://christfellowshipchurch.atlassian.net/browse/CFDP-1281
> Patch profile image upload
