- src/index.js
- src/ui/Onboarding/Onboarding.stories.js
- src/ui/Onboarding/index.js
- src/ui/Onboarding/slides/EnableNotifications/form.js
- src/ui/Onboarding/slides/EnableNotifications/index.js
- src/ui/Onboarding/slides/Identity/form.js
- src/ui/Onboarding/slides/Identity/index.js
- src/ui/Onboarding/slides/Passcode/form.js
- src/ui/Onboarding/slides/Passcode/index.js
- src/ui/Onboarding/slides/ProfileInformation/form.js
- src/ui/Onboarding/slides/ProfileInformation/index.js
- src/ui/Onboarding/slides/containers.js
- src/ui/Onboarding/slides/styles.js
Made some updates to the on boarding process per bugs that were found.
> Onboarding fixes

- src/tabs/more/events/index.js
- src/tabs/more/events/queries.js
- src/ui/ContentCardConnected/index.js
- src/ui/ContentCardConnected/query.js
Adds nextOccurrence as a query field and orders lists by that field
> Updated queries to remove startDate endDate from EventContentItem

- src/content-single/EventDateTimes/index.js
* addresses will no longer show in the EventSchedule card of an Event Detail item
> [CFDP-497] Removed Address from Events item

- loadConfig.js
- src/content-single/Author/index.js
- src/content-single/Author/queries.js
- src/content-single/EventContentItem/index.js
- src/content-single/UniversalContentItem/index.js
- src/content-single/getContentItem.js
* added author name and photo
* added publish date
* added a calculate read time
> [CFDP-400] Added Author, Publish Date, and Read Time

- appcenter-pre-build.sh
- src/content-single/EventDateTimes/index.js
- src/content-single/InformationalContentItem/index.js
- src/tabs/tabBar.js
- src/theme/dark-theme.js
- src/ui/StatusBar/index.js
Resolves the following Jira tickets:
[CFDP-498]
[CFDP-578]
[CFDP-574]
[CFDP-498]: https://christfellowshipchurch.atlassian.net/browse/CFDP-498
[CFDP-578]: https://christfellowshipchurch.atlassian.net/browse/CFDP-578
[CFDP-574]: https://christfellowshipchurch.atlassian.net/browse/CFDP-574
> Launch bugs

- src/bugsnag.js
- src/client/index.js
- src/index.js
Mimics NewSpring's bugsnag setup to better capture errors related to a phanom authentication bug
https://github.com/NewSpring/corinth/blob/master/src/bugsnag.js
> NewSpring Bugsnag setup

- src/content-single/Author/index.js
* Removed 'readTime' from articles
> [CFDP-631] Removed 'readTime' from articles

- README.md
> Update Apollos Project link in readme to point to correct  url

- loadConfig.js
- src/edit-user/EditUser.js
- src/edit-user/index.js
- src/hooks/useCurrentUser.js
- src/ui/inputs/DateInput.js
- src/ui/inputs/Picker.js
Every field runs the update mutation on change instead of tracking each change and running them collectively.
> Fixed profile editing errors

- src/edit-user/UpdatePushNotification.js
Using logic from our Onboarding experience, the update notification button text updates instantly after first prompt. From there text will say 'Update Notifications in Settings'
> Updated logic for updating push notifications

- src/edit-user/EditUser.js
- src/ui/inputs/Picker.js
Fixed Update Address in Profile and picker
> Fixed Update Address in Profile and picker

- src/theme/theme.js
* Added new copy for `ui-prayer` components
* update "I'm thankful for..." text inside of placeholder
> [CFDP-806] Updated copy for ui-prayer

- package.json
Updated ui-prayer in order to show correct text in place holder.
> Updated ui-prayer to 1.4.4-alpha.14

- src/group-single/GroupSingle.js
- src/group-single/VideoCall.js
- src/ui/Cards/HorizontalGroupCard/index.js
> Fixes dates and only take attendance on date of meeting

- src/group-single/GroupSingle.js
- src/group-single/getGroup.js
- src/tabs/connect/Groups/getCurrentUserGroups.js
> Remove leaders photo from primary avatar on GroupSingle

- src/ui/Cards/HorizontalGroupCard/index.js
- src/ui/Cards/HorizontalPrayerRequestCard/index.js
> Fix Groups Dark theme/mode

- src/group-single/GroupSingle.js
- src/group-single/getGroup.js
- src/tabs/connect/Groups/getCurrentUserGroups.js
- src/ui/Cards/HorizontalGroupCard/index.js
- src/ui/DateLabel/index.js
> Adjust DateLabel to account for times and add to GroupSingle

- src/group-single/GroupSingle.js
> Truncate member name to avoid breaking to newline

- src/group-single/Resources.js
Previous button styles looked like the button was not clickable.
> Improve resource button styles

- src/group-single/GroupSingle.js
- src/group-single/VideoCall.js
- src/group-single/getGroup.js
User `A` doesn't have a nickName, `Barry Allen` does ⚡️. Nick names will also be the default in Zoom/Video Calls.
> Use nickName as default and fallback to firstName in Groups

- src/group-single/GroupSingle.js
- src/ui/Cards/HorizontalGroupCard/index.js
Gives avatars a little breathing room near the edges and titles.
> Add padding to avatar cloud

- src/tabs/connect/Groups/index.js
- src/ui/Cards/HorizontalGroupCard/index.js
Group cards now have working background images.
> Fix group card background image

- src/hooks/WithFeatureFlag.js
- src/hooks/index.js
- src/media-player/controls/LiveStreamControls.js
This sets up the useFeatureFlag hook so we can use it in class components and adds a feature flag check to the landscape chat feature.
> Add WithFeatureFlag for landscape chat

- src/group-single/Resources.js
Adds group resource interaction using interactWithNode.
Go to any group and click on a resource. Verify that the interaction is recorded in Rock.
| iOS | Android |
**Manual QA**
**Code Review**
> The purpose of PR Review is to _improve the quality of the software._
> Add group resource interaction

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/christfellowship/MainActivity.java
- android/app/src/main/java/com/christfellowship/MainApplication.java
- ios/ChristFellowship/AppDelegate.m
- ios/Podfile.lock
- package.json
- src/content-single/ContentSingle.js
- src/index.js
- src/media-player/index.js
- src/screen-orientation/index.js
- src/screen-orientation/package.json
- yarn.lock
Lock the orientation of the app to a portrait orientation.
Our app currently supports both Portrait and Landscape orientations. Since the content is not designed/optimized for a landscape experience, there is some strange behavior exhibited when rotating your device
* We cannot disable landscape orientations because of restrictions with Apple. Instead, a package ([react-native-orientation-locker](https://www.npmjs.com/package/react-native-orientation-locker)) has been introduced to keep the content in a static orientation
* Tablets should still have the ability to change orientation
* When a video is playing, users should be able to adjust the orientation of their device
Load up the app and change the orientation.
| iOS | Android |
| --- | ------- |
| …
> Lock Orientation of App to Portrait

- src/chat/Channel.js
- src/index.js
- src/ui/Cards/GroupCard/index.js
When a user closes/navigates out of a group chat they end up on the profile screen instead of the group single modal/view.
This removes the title of the group from group chat header in hopes that a user understands that when they click into `message group` they still know who they are messaging. This allows us to keep the modal header consistent with other modals in the app.
Go to any of your groups and click in to `message group` close chat and make sure you are navigated back to the group single view not the profile tab.
Also, navigate to any other chat instances and make sure there are not an side effects or regressions created by this PR.
| iOS | Android |
| --- | ------- |
|![image](https://user-images.githubusercontent.com/2528817/101212928-2d8d3300-363f-11eb-808a-7e382a4bf7d7.png)|! …
> Fix group chat back button bug

- src/context/NotificationsProvider.js
- src/context/ProvidersStack.js
- src/context/UniversalLinkRouteProvider.js
- src/hooks/useLinkRouter.js
- src/index.js
- src/stream-chat/components/ChatChannelList.js
- src/stream-chat/context/index.js
- src/theme/context/ApollosThemeProvider.js
- src/theme/context/index.js
* Moves the theme provider to the /theme/context directory
* Patches the structure of the Providers to always ensure proper access to the `navigation` object from the NavigationContainer
> Updates Providers structure

- src/features/FeaturesFeed/FeaturesFeedConnected/index.js
Manually rewrites the refetch functionality since the one provided as a part of the `useQuery` hook and applied it to:
* Pull to refresh
* App Background --> App Foreground Focus
[CFDP-1521]
[Loom Recording/Explanation](https://www.loom.com/share/e4dfb56dac4c4daeb44d8cac82a38848)
[CFDP-1521]: https://christfellowshipchurch.atlassian.net/browse/CFDP-1521
> Implements a manual `refetch` method
